enum IActions {
  SELECT_DISTANCE = "SELECT_DISTANCE",
  SELECT_TEMPERATURE = "SELECT_TEMPERATURE",
  SELECT_PLACE = "SELECT_PLACE",
  ADD_LOCATION = "ADD_LOCATION",
  REMOVE_LOCATION = "REMOVE_LOCATION",
};

export default IActions;